// <auto-generated />
using System;
using APIClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIClub.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20251207194737_siembraInicial")]
    partial class siembraInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("APIClub.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Cuotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2024,
                            FechaPago = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 1,
                            Monto = 2500.00m,
                            Semestre = 1,
                            SocioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2024,
                            FechaPago = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 2,
                            Monto = 2500.00m,
                            Semestre = 2,
                            SocioId = 1
                        });
                });

            modelBuilder.Entity("APIClub.Models.MontoCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoCuotaFija")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MontoCuota");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaActualizacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoCuotaFija = 2500.00m
                        });
                });

            modelBuilder.Entity("APIClub.Models.ReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("SocioId");

                    b.ToTable("ReservasSalones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAlquiler = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 5000.00m,
                            SalonId = 1,
                            SocioId = 1,
                            TotalPagado = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            FechaAlquiler = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 7000.00m,
                            SalonId = 2,
                            SocioId = 2,
                            TotalPagado = 7000.00m
                        });
                });

            modelBuilder.Entity("APIClub.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Falsa 123",
                            Name = "Salón Central"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Siempre Viva 742",
                            Name = "Salón Norte"
                        });
                });

            modelBuilder.Entity("APIClub.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direcccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaAsociacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Direcccion = "Mitre 100",
                            Dni = "12345678",
                            FechaAsociacion = new DateOnly(2020, 5, 10),
                            Localidad = "Rosario",
                            Nombre = "Juan",
                            Telefono = "341-1234567"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            Direcccion = "San Martín 200",
                            Dni = "87654321",
                            FechaAsociacion = new DateOnly(2021, 3, 15),
                            Localidad = "Córdoba",
                            Nombre = "María",
                            Telefono = "341-7654321"
                        });
                });

            modelBuilder.Entity("APIClub.Models.Cuota", b =>
                {
                    b.HasOne("APIClub.Models.Socio", "Socio")
                        .WithMany("HistorialCuotas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Models.ReservaSalon", b =>
                {
                    b.HasOne("APIClub.Models.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIClub.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Models.Socio", b =>
                {
                    b.Navigation("HistorialCuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
